"""
DataPilot AI - Report Generator Module
Compiles executive analytical reports into text, CSV, and downloadable artifacts.
"""

from typing import Dict, Any
import json

def generate_text_report(report_data: Dict[str, Any]) -> str:
    """
    Compiles complete plain-text executive summary report.
    """
    ds = report_data.get("overview", {})
    dq = report_data.get("quality", {})
    ml = report_data.get("ml", {})
    insights = report_data.get("insights", "")

    txt = []
    txt.append("=" * 70)
    txt.append("DATAPILOT AI — EXECUTIVE DATA ANALYSIS & ML REPORT")
    txt.append("Developed By: Swapna V")
    txt.append("Role:         Agentic AI Engineer")
    txt.append("Organization: IPCET Solutions")
    txt.append("=" * 70)
    txt.append("")

    # 1. Dataset Summary
    txt.append("1. DATASET OVERVIEW")
    txt.append("-" * 35)
    txt.append(f"File Name:            {ds.get('filename', 'dataset.csv')}")
    txt.append(f"Total Rows:           {ds.get('rows', 0):,}")
    txt.append(f"Total Columns:        {ds.get('columns', 0)}")
    txt.append(f"Numerical Columns:    {ds.get('num_count', 0)}")
    txt.append(f"Categorical Columns:  {ds.get('cat_count', 0)}")
    txt.append(f"Missing Values:       {ds.get('missing_values', 0)}")
    txt.append(f"Duplicate Rows:       {ds.get('duplicate_rows', 0)}")
    txt.append(f"Memory Usage:         {ds.get('memory_usage', 'N/A')}")
    txt.append("")

    # 2. Data Quality Score
    txt.append("2. DATA QUALITY AUDIT")
    txt.append("-" * 35)
    txt.append(f"Data Quality Score:   {dq.get('score', 100)} / 100")
    txt.append(f"Missing Values Rate:  {dq.get('missing_pct', 0)}%")
    txt.append(f"Duplicates Rate:      {dq.get('duplicates_pct', 0)}%")
    txt.append(f"Outliers Rate:        {dq.get('outliers_pct', 0)}%")
    if dq.get("recommendations"):
        txt.append("\nRecommendations for Improvement:")
        for rec in dq.get("recommendations", []):
            txt.append(f"  • {rec}")
    txt.append("")

    # 3. Data Cleaning Summary
    cleaning_actions = report_data.get("cleaning_actions", [])
    txt.append("3. DATA CLEANING ACTIONS")
    txt.append("-" * 35)
    if cleaning_actions:
        for act in cleaning_actions:
            txt.append(f"  ✓ {act}")
    else:
        txt.append("  No automated cleaning actions required.")
    txt.append("")

    # 4. Machine Learning & Model Comparison
    txt.append("4. MACHINE LEARNING & MODEL EVALUATION")
    txt.append("-" * 35)
    txt.append(f"Target Column:        {ml.get('target_col', 'N/A')}")
    txt.append(f"Problem Type:         {ml.get('problem_type', 'N/A')}")
    txt.append(f"Best Model Selected:  {ml.get('best_model_name', 'N/A')}")
    txt.append(f"Best Model Score:     {ml.get('best_score_formatted', 'N/A')}")
    txt.append("")

    comparison = ml.get("comparison_table", [])
    if comparison:
        txt.append("Model Comparison Table:")
        txt.append(f"{'Model':<30} | {'Score':<10}")
        txt.append("-" * 45)
        for row in comparison:
            m_name = row.get("Model", "")
            m_sc = row.get("Score", "")
            txt.append(f"{m_name:<30} | {m_sc:<10}")
        txt.append("")

    # 5. Top Feature Importance
    top_feats = ml.get("feature_importance", [])
    if top_feats:
        txt.append("Top Predictive Features:")
        for idx, item in enumerate(top_feats, 1):
            txt.append(f"  {idx}. {item.get('feature'):<24} {item.get('importance')}%")
        txt.append("")

    # 6. AI Insights
    txt.append("5. AI-GENERATED BUSINESS INSIGHTS")
    txt.append("-" * 35)
    txt.append(insights if insights else "No AI insights generated.")
    txt.append("")
    txt.append("=" * 70)
    txt.append("Generated by DataPilot AI — Built with Streamlit, Scikit-learn & Gemini")
    txt.append("=" * 70)

    return "\n".join(txt)
