import JSZip from 'jszip';
import Papa from 'papaparse';
import {
  DatasetOverview,
  DataQualityAudit,
  MlExperimentResult,
  DataRow
} from '../types/dataPilot';

export function buildTextReport(
  overview: DatasetOverview,
  quality: DataQualityAudit,
  cleaningActions: string[],
  mlResult: MlExperimentResult | null,
  insights: string
): string {
  const lines: string[] = [];
  lines.push('======================================================================');
  lines.push('DATAPILOT AI — EXECUTIVE DATA ANALYSIS & ML REPORT');
  lines.push('Developed By: Swapna V');
  lines.push('Role:         Agentic AI Engineer');
  lines.push('Organization: IPCET Solutions');
  lines.push('======================================================================\n');

  lines.push('1. DATASET OVERVIEW');
  lines.push('-----------------------------------');
  lines.push(`File Name:            ${overview.filename}`);
  lines.push(`Total Rows:           ${overview.rows.toLocaleString()}`);
  lines.push(`Total Columns:        ${overview.columns}`);
  lines.push(`Numerical Columns:    ${overview.numCount}`);
  lines.push(`Categorical Columns:  ${overview.catCount}`);
  lines.push(`Missing Values:       ${overview.missingValues}`);
  lines.push(`Duplicate Rows:       ${overview.duplicateRows}`);
  lines.push(`Memory Usage:         ${overview.memoryUsage}\n`);

  lines.push('2. DATA QUALITY AUDIT');
  lines.push('-----------------------------------');
  lines.push(`Data Quality Score:   ${quality.score} / 100`);
  lines.push(`Missing Values Rate:  ${quality.missingPct}%`);
  lines.push(`Duplicates Rate:      ${quality.duplicatesPct}%`);
  lines.push(`Outliers Rate:        ${quality.outliersPct}%`);
  lines.push('\nRecommendations:');
  quality.recommendations.forEach((r) => lines.push(`  • ${r}`));
  lines.push('');

  lines.push('3. DATA CLEANING AUDIT');
  lines.push('-----------------------------------');
  if (cleaningActions.length > 0) {
    cleaningActions.forEach((a) => lines.push(`  ✓ ${a}`));
  } else {
    lines.push('  No automated modifications applied.');
  }
  lines.push('');

  lines.push('4. MACHINE LEARNING & MODEL EVALUATION');
  lines.push('-----------------------------------');
  if (mlResult) {
    lines.push(`Target Feature:       ${mlResult.targetCol}`);
    lines.push(`Problem Type:         ${mlResult.problemType}`);
    lines.push(`Best Model:           ${mlResult.bestModelName}`);
    lines.push(`Performance Score:    ${mlResult.bestScoreFormatted}\n`);

    lines.push('Model Comparison Table:');
    lines.push(`${'Model'.padEnd(32)} | Score`);
    lines.push('-----------------------------------------');
    mlResult.comparisonTable.forEach((m) => {
      lines.push(`${m.model.padEnd(32)} | ${m.score}`);
    });
    lines.push('');

    if (mlResult.featureImportance.length > 0) {
      lines.push('Top Predictive Features:');
      mlResult.featureImportance.forEach((fi, idx) => {
        lines.push(`  ${idx + 1}. ${fi.feature.padEnd(24)} ${fi.importance}%`);
      });
      lines.push('');
    }
  } else {
    lines.push('No machine learning models trained yet.');
    lines.push('');
  }

  lines.push('5. AI-GENERATED BUSINESS INSIGHTS');
  lines.push('-----------------------------------');
  lines.push(insights || 'No insights generated yet.\n');

  lines.push('======================================================================');
  lines.push('Generated by DataPilot AI — Architecture by Swapna V');
  lines.push('======================================================================');

  return lines.join('\n');
}

export function buildHTMLReport(
  overview: DatasetOverview,
  quality: DataQualityAudit,
  cleaningActions: string[],
  mlResult: MlExperimentResult | null,
  insights: string
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>DataPilot AI — Executive Analysis Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #1e293b; max-width: 900px; margin: 40px auto; padding: 0 20px; }
    h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
    h2 { color: #1e293b; margin-top: 32px; border-bottom: 1px solid #f1f5f9; padding-bottom: 8px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-weight: 600; font-size: 14px; background: #e0e7ff; color: #3730a3; }
    .metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin: 20px 0; }
    .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; }
    .card .val { font-size: 24px; font-weight: 700; color: #0284c7; }
    .card .lbl { font-size: 12px; text-transform: uppercase; color: #64748b; font-weight: 600; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { padding: 10px 14px; text-align: left; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
    th { background: #f1f5f9; font-weight: 600; }
    pre { background: #f8fafc; border: 1px solid #e2e8f0; padding: 16px; border-radius: 8px; white-space: pre-wrap; font-family: monospace; }
  </style>
</head>
<body>
  <h1>🚀 DataPilot AI — Executive Analytics & ML Report</h1>
  <p><strong>Developed By:</strong> Swapna V &bull; <strong>Role:</strong> Agentic AI Engineer &bull; <strong>Organization:</strong> IPCET Solutions &bull; ${new Date().toLocaleDateString()}</p>
  
  <h2>1. Dataset Overview</h2>
  <div class="metric-grid">
    <div class="card"><div class="lbl">Total Rows</div><div class="val">${overview.rows.toLocaleString()}</div></div>
    <div class="card"><div class="lbl">Columns</div><div class="val">${overview.columns}</div></div>
    <div class="card"><div class="lbl">Numerical</div><div class="val">${overview.numCount}</div></div>
    <div class="card"><div class="lbl">Categorical</div><div class="val">${overview.catCount}</div></div>
  </div>

  <h2>2. Data Quality Score: ${quality.score} / 100</h2>
  <ul>
    ${quality.recommendations.map((r) => `<li>${r}</li>`).join('')}
  </ul>

  <h2>3. Machine Learning Performance</h2>
  ${
    mlResult
      ? `<p><strong>Target Feature:</strong> ${mlResult.targetCol} (${mlResult.problemType})<br>
         <strong>Best Model:</strong> ${mlResult.bestModelName} (<strong>${mlResult.bestScoreFormatted}</strong>)</p>
         <table>
           <thead><tr><th>Model Architecture</th><th>Performance Score</th></tr></thead>
           <tbody>
             ${mlResult.comparisonTable.map((m) => `<tr><td>${m.model}</td><td><strong>${m.score}</strong></td></tr>`).join('')}
           </tbody>
         </table>`
      : '<p>No model trained.</p>'
  }

  <h2>4. AI Insights & Strategic Recommendations</h2>
  <pre>${insights || 'No insights generated.'}</pre>
</body>
</html>`;
}

export function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadCleanedCSV(data: DataRow[], filename: string) {
  const csv = Papa.unparse(data);
  downloadBlob(csv, filename, 'text/csv;charset=utf-8;');
}

/**
 * Creates and downloads a complete ZIP containing the Python Streamlit project repository!
 */
export async function downloadPythonRepositoryZip(sampleDataCsvText: string) {
  const zip = new JSZip();

  // Root files
  zip.file(
    'requirements.txt',
    `streamlit>=1.35.0
pandas>=2.2.0
numpy>=1.26.0
matplotlib>=3.8.0
seaborn>=0.13.0
scikit-learn>=1.4.0
joblib>=1.3.0
openpyxl>=3.1.0
plotly>=5.22.0
google-genai>=0.1.1
python-dotenv>=1.0.0
`
  );

  zip.file(
    '.gitignore',
    `__pycache__/
*.py[cod]
*$py.class
venv/
.env
.DS_Store
models/*.joblib
`
  );

  zip.file(
    '.env.example',
    `# GEMINI_API_KEY: Optional for AI-Powered Insights
GEMINI_API_KEY="YOUR_GEMINI_API_KEY"
`
  );

  zip.file(
    'README.md',
    `# DataPilot AI — AI-Powered Data Analysis & Machine Learning Assistant
Developed By: Swapna V
Role: Agentic AI Engineer
Organization: IPCET Solutions

## Quick Start
1. pip install -r requirements.txt
2. streamlit run app.py
`
  );

  // Data folder
  const dataFolder = zip.folder('data');
  dataFolder?.file('sample_data.csv', sampleDataCsvText);

  // Models folder
  const modelsFolder = zip.folder('models');
  modelsFolder?.file('.gitkeep', '# Serialized joblib models\n');

  // Let's fetch local module files or embed them
  try {
    const appPyRes = await fetch('/app.py');
    if (appPyRes.ok) zip.file('app.py', await appPyRes.text());
  } catch (e) {}

  const modules = [
    '__init__.py',
    'data_loader.py',
    'data_cleaning.py',
    'data_quality.py',
    'eda.py',
    'visualization.py',
    'ml_models.py',
    'prediction.py',
    'ai_insights.py',
    'report_generator.py'
  ];

  const modulesFolder = zip.folder('modules');
  for (const m of modules) {
    try {
      const res = await fetch(`/modules/${m}`);
      if (res.ok) {
        modulesFolder?.file(m, await res.text());
      }
    } catch (e) {}
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'DataPilot-AI-Streamlit-Project.zip';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
